language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
  licenses:
     - 'android-sdk-preview-license-.+'
     - 'android-sdk-license-.+'
     - 'google-gdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

matrix:
  include:
    - stage: "Build Demo Debug"
      script: ./gradlew clean lintDemoDebug assembleDemoDebugUnitTest assembleDemoDebug
    - stage: "Build Demo Release"
      script: ./gradlew clean lintDemoRelease assembleDemoReleaseUnitTest assembleDemoRelase
    - stage: "Build Full Debug"
      script: ./gradlew clean lintFullDebug assembleFullDebugUnitTest assembleFullDebug
    - stage: "Build Full Release"
      script: ./gradlew clean lintFullRelease assembleFullReleaseUnitTest assembleFullRelease