language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
  licenses:
     - 'android-sdk-preview-license-.+'
     - 'android-sdk-license-.+'
     - 'google-gdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

matrix:
  include:
    - stage: "Build"
      name: "Demo debug version"
      script: ./gradlew assembleDemoDebug
    - script: ./gradlew assembleFullDebug
      name: "Full debug version"
    - script: ./gradlew assembleDemoRelease
      name: "Demo release version"
    - script: ./gradlew assembleFullRelease
      name: "Full release version"

    - stage: "Verification"
      name: "Lint"
      script: ./gradlew lint
    - script: ./gradlew test
      name: "Test"

    - stage: "Deploy"
      name: "Deploy somewhere"
      script: bash ./script/deploy_somewhere.sh
    - script: bash ./script/deploy_somewhere_else.sh
      name: "Deploy somewhere else"
